import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1280, height: 800 }, deviceScaleFactor: 1.5 });
await p.goto('http://localhost:8145/empresas-local.html', { waitUntil: 'load' });
await p.waitForSelector('.emp-hero-video', { timeout: 8000 });
await p.waitForTimeout(1500);
const v = await p.evaluate(() => { const el=document.querySelector('.emp-hero-video'); return { vw: el.videoWidth, vh: el.videoHeight, paused: el.paused, ct: +el.currentTime.toFixed(2) }; });
console.log('video:', JSON.stringify(v));
await p.screenshot({ path: '/tmp/emp-hero.png', clip:{x:0,y:0,width:1280,height:560} });
await b.close();
