import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport:{width:1180,height:760}, deviceScaleFactor:1.5 });
await p.goto('http://localhost:8153/empresas-local.html', { waitUntil:'load' });
await p.waitForSelector('.emp-sector-chip', { timeout:9000 });
const r = await p.evaluate(()=>{ const c=getComputedStyle(document.querySelector('.emp-sector-chip')); return { radius:c.borderTopLeftRadius+'/'+c.borderTopRightRadius, border:c.borderColor }; });
console.log('chip:', JSON.stringify(r));
await p.evaluate(()=>document.querySelector('.emp-sectors-sec').scrollIntoView());
await p.waitForTimeout(400);
await p.screenshot({ path:'/tmp/emp-sectors.png' });
await b.close();
