#!/usr/bin/env node
/**
 * scripts/build-jsx.js
 *
 * Precompila docs/components/*.jsx → docs/components/*.js usando
 * @babel/core + @babel/preset-react. Equivalente a lo que hacía
 * Babel standalone en el cliente, pero ejecutado UNA SOLA VEZ
 * localmente y commiteado al repo.
 *
 * Uso:
 *   npm install --no-save @babel/core @babel/preset-react
 *   node scripts/build-jsx.js
 *
 * O añadir a package.json (gitignored):
 *   "scripts": { "build:jsx": "node scripts/build-jsx.js" }
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const babel = require('@babel/core');

const SRC_DIR = path.join(__dirname, '..', 'docs', 'components');
const DOCS_DIR = path.join(__dirname, '..', 'docs');
const PRESETS = [
  ['@babel/preset-react', { runtime: 'classic' }],
];

const banner =
  '// AUTO-GENERATED — do not edit. Source: same filename with .jsx extension.\n' +
  '// Generated by scripts/build-jsx.js using @babel/preset-react.\n';

let ok = 0, fail = 0;
const files = fs.readdirSync(SRC_DIR).filter(f => f.endsWith('.jsx'));

console.log(`Compiling ${files.length} JSX files from ${SRC_DIR}…\n`);

for (const file of files) {
  const srcPath = path.join(SRC_DIR, file);
  const outPath = path.join(SRC_DIR, file.replace(/\.jsx$/, '.js'));
  const src = fs.readFileSync(srcPath, 'utf8');
  try {
    const result = babel.transformSync(src, {
      presets: PRESETS,
      filename: file,
      babelrc: false,
      configFile: false,
      sourceMaps: false,
      compact: false,  // legible output
    });
    fs.writeFileSync(outPath, banner + result.code + '\n');
    const inSize = (src.length / 1024).toFixed(1);
    const outSize = (result.code.length / 1024).toFixed(1);
    console.log(`  ✓ ${file.padEnd(35)} ${inSize} KB → ${outSize} KB`);
    ok++;
  } catch (err) {
    console.error(`  ✗ ${file}: ${err.message}`);
    fail++;
  }
}

console.log(`\nDone. ${ok} compiled, ${fail} failed.`);

if (fail === 0) {
  // Stamp a content hash of the compiled components into every HTML loader
  // (?cv=…). Lets browsers cache component JS (the big payload) while still
  // busting on deploy. Data JSON keeps its own no-store fetch untouched.
  const hash = crypto.createHash('md5');
  for (const file of fs.readdirSync(SRC_DIR).filter(f => f.endsWith('.js')).sort()) {
    hash.update(fs.readFileSync(path.join(SRC_DIR, file)));
  }
  const cv = hash.digest('hex').slice(0, 10);

  let stamped = 0;
  for (const html of fs.readdirSync(DOCS_DIR).filter(f => f.endsWith('.html'))) {
    const p = path.join(DOCS_DIR, html);
    const before = fs.readFileSync(p, 'utf8');
    const after = before.replace(/\?cv=[a-z0-9]*/g, '?cv=' + cv);
    if (after !== before) { fs.writeFileSync(p, after); stamped++; }
  }
  console.log(`Component version cv=${cv} stamped in ${stamped} HTMLs.`);
}

process.exit(fail > 0 ? 1 : 0);
